### ISSUE TITLE
问题： 为何改变DNS能解锁只供大陆的内容？

### ISSUE THREAD

**Issue by kun-zhou** [uku/Unblock-Youku#774]
I am wondering how does switching name server affects the accessibility of blocked contents? For instance, I live in the US, and after changing my DNS, my public IP did not change (as expected), but Netease Music seems to be allowing me to download stuff that was previously only intended for mainland users. Merely changing the DNS shouldn't matter assuming I get the same IP address for the domain names I am querying. But then why is it working?

**Comment by tommyzhaozbh** [comment]
That's simply a DNS reverse proxy. When accessing any url, the devices always need to send an inquiry to the DNS server to get the IP address. This DNS will direct you to the proxy server rather than the server of netease while accessing specific URL. However, while accessing non-restricted website, the DNS will redirect your request to Google DNS and you will connect the website server directly. So no proxy will be detected.

**Comment by kun-zhou** [comment]
Oh, I see. Thanks!
